version: '3.9'

services:
  app:
    container_name: gunmaweb-53-app
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      - NODE_ENV=development
